In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(1)

In [3]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [4]:
def sigmoid_derivative(x):
    return x*(1-x)

In [5]:
#this is a 10 by 10 matrix of random numbers, between -1 and 1
#this represents all connections, every input neuron is connected to every "otherlayer"-s neuron
weights = 2 * np.random.random((3,3)) - 1
print(weights)

[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]]


In [6]:
def train(iterations, X_train,y_train):
    input_layer = X_train    #just for naming
    for i in range(iterations):
        global weights 
        outputs = (sum(sigmoid(np.dot(input_layer, weights))))/y_train.size   
        if i == 1:
            print("first predictions are: " ,outputs)   #printing first predictions
        error = y_train - outputs
        adjustments = error * sigmoid_derivative(outputs)
        #adjusting:
        weights += np.dot(input_layer.T , adjustments)

Adjusting weights by = error.imput.derivative_of_sigmoid(output)

derivative of sigmoid = x*(1-x)

In [7]:
def validate(test):
    return (sum((sigmoid(np.dot(test, weights)))))/test.size

In [8]:
#Data 1
X_train = np.array([[0,1,1],
                    [1,0,1],
                    [1,1,1],
                       ])
y_train = np.array([1,1,0]).T   #the output should be the first element of the input vector in this "dataset"
# .T means tranform, we have to make y to a column

In [9]:
train(10000, X_train, y_train)

first predictions are:  [0.32368268 0.44613043 0.31024321]


In [10]:
predictions = validate(X_train)    #there is no cross validation yet, we test the training data

In [11]:
predictions

array([0.13682283, 0.33333333, 0.33333333])