In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(1)

In [3]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [4]:
def sigmoid_derivative(x):
    return x*(1-x)

In [5]:
#this is a 4 by 1 matrix of random numbers, between -1 and 1
weights = 2 * np.random.random((4,)) - 1
print(weights)

[-0.16595599  0.44064899 -0.99977125 -0.39533485]


In [6]:
def train(iterations, X_train, y_train):
    input_layer = X_train    #just for naming
    for i in range(iterations):
        global weights 
        outputs = sigmoid(np.dot(input_layer, weights))   #dot producto of input vector and weight matrix
        if i == 1:
            print("first predictions are: " ,outputs)   #printing first predictions
        error = y_train - outputs
        adjustments = error * sigmoid_derivative(outputs)
        #adjusting:
        weights += np.dot(input_layer.T , adjustments)

Adjusting weights by = error.imput.derivative_of_sigmoid(output)

derivative of sigmoid = x*(1-x)

In [7]:
def validate(test):
    return sigmoid(np.dot(test, weights))

In [10]:
# Data 3
X_train = np.array([[0,0,0,1],
                    [0,1,1,0],
                    [1,1,1,0],
                    [1,1,1,1],
                    [0,0,0,0]])
y_train = np.array([0,0,1,1,0]).T   

In [11]:
train(100000, X_train, y_train)

first predictions are:  [0.41283196 0.46216937 0.49259348 0.40566904 0.5       ]


In [12]:
predictions = validate(X_train)    #there is no cross validation yet, we test the training data

In [13]:
predictions

array([0.00451094, 0.00421876, 0.99998224, 0.99609485, 0.5       ])

In [14]:
y_train

array([0, 0, 1, 1, 0])